# Generated by Django 3.2.7 on 2021-10-04 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='passlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.PositiveSmallIntegerField(choices=[(1, 'Social Media'), (2, 'E-mail'), (3, 'Bank'), (4, 'Credit Card'), (5, 'Peduli Lindungi'), (6, 'Trading'), (7, 'E-Commerce')], default=4)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
