# Generated by Django 3.2.7 on 2021-10-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0002_alter_passlist_appname'),
    ]

    operations = [
        migrations.AddField(
            model_name='passlist',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
