# Generated by Django 3.2.7 on 2021-10-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0003_passlist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passlist',
            old_name='appname',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='passlist',
            old_name='name',
            new_name='application_name',
        ),
    ]
